spring.application.name=spring-web-market-app

#DB Settings
spring.sql.init.mode=always
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/webapp
spring.r2dbc.username=postgres
spring.r2dbc.password=admin




