CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50)    NOT NULL,
    description VARCHAR(255)   NOT NULL,
    price       NUMERIC(12, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date TIMESTAMP DEFAULT NOW() not null
);

CREATE TABLE IF NOT EXISTS order_items
(
    order_id BIGINT  NOT NULL,
    item_id  BIGINT  NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),

    PRIMARY KEY (order_id, item_id),

    CONSTRAINT fk_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,


    CONSTRAINT fk_item
        FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE RESTRICT
);