CREATE TABLE IF NOT EXISTS goods
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255)   NOT NULL,
    price       NUMERIC(12, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS goods_images
(
    good_id      BIGINT PRIMARY KEY REFERENCES goods (id) ON DELETE CASCADE,
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size    BIGINT       NOT NULL,
    file_data    BYTEA        NOT NULL
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    good_id     INTEGER REFERENCES goods (id) ON DELETE CASCADE,
    order_quant INTEGER NOT NULL,
    PRIMARY KEY (order_id, good_id)
);