spring.application.name=spring-web-market-app

server.port=9090

#DB Settings
spring.sql.init.mode=always
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/webapp
spring.r2dbc.username=postgres
spring.r2dbc.password=admin

app.payment.base-url=http://localhost:8081

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=-1ms
cart.ttl.minutes=15

#Mock
mock.appl.userid=123
mock.appl.token=12345

#Keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/web-market-app
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=yandex-web-market
spring.security.oauth2.client.registration.keycloak.client-secret=HXqtbQr7P0ZWU1nH8CdCCVzK4s2mJ8EO
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email




