DROP TABLE items, orders, order_items;

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50)    NOT NULL,
    description VARCHAR(255)   NOT NULL,
    img_path  VARCHAR(255),
    price       NUMERIC(12, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date TIMESTAMP DEFAULT NOW() not null
);

CREATE TABLE IF NOT EXISTS order_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT  NOT NULL,
    item_id  BIGINT  NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),

    CONSTRAINT fk_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,

    CONSTRAINT fk_item
        FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE RESTRICT,

    CONSTRAINT uk_order_item UNIQUE (order_id, item_id)
);